#!/bin/bash

# Script to verify 16 KB page size alignment in AAB bundle
# This helps identify which native libraries might be causing issues

echo "=========================================="
echo "16 KB Page Size Alignment Verification"
echo "=========================================="
echo ""

AAB_FILE="android/app/build/outputs/bundle/release/app-release.aab"

if [ ! -f "$AAB_FILE" ]; then
    echo "❌ AAB file not found: $AAB_FILE"
    echo "   Please build the bundle first: ./gradlew bundleRelease"
    exit 1
fi

echo "✅ Found AAB: $AAB_FILE"
echo ""

# Check zip alignment using bundletool
echo "1. Checking zip alignment configuration..."
ALIGNMENT=$(bundletool dump config --bundle="$AAB_FILE" 2>/dev/null | grep -i "alignment" | grep -o '"[^"]*"' | tr -d '"')
if [ "$ALIGNMENT" = "PAGE_ALIGNMENT_16K" ]; then
    echo "   ✅ Zip alignment: $ALIGNMENT (CORRECT)"
else
    echo "   ❌ Zip alignment: $ALIGNMENT (SHOULD BE PAGE_ALIGNMENT_16K)"
fi
echo ""

# Extract and check native libraries
echo "2. Extracting AAB to check native libraries..."
TEMP_DIR=$(mktemp -d)
unzip -q "$AAB_FILE" -d "$TEMP_DIR" 2>/dev/null

# Find all .so files
SO_FILES=$(find "$TEMP_DIR" -name "*.so" 2>/dev/null)

if [ -z "$SO_FILES" ]; then
    echo "   ⚠️  No native libraries found in AAB"
    echo "   (Native libraries are in split APKs generated by Google Play)"
else
    echo "   Found native libraries:"
    for so_file in $SO_FILES; do
        echo "   - $(basename "$so_file")"
    done
    echo ""
    echo "   Note: To check ELF alignment, use: readelf -l <library.so> | grep LOAD"
    echo "   Look for 'Align' field - should be 16384 (0x4000) for 16 KB alignment"
fi

# Cleanup
rm -rf "$TEMP_DIR"

echo ""
echo "=========================================="
echo "Next Steps:"
echo "=========================================="
echo "1. If zip alignment is PAGE_ALIGNMENT_16K: ✅ Bundle configuration is correct"
echo "2. If Google Play still rejects:"
echo "   - Some third-party libraries may have non-16KB-aligned native code"
echo "   - Check these libraries: react-native-reanimated, Firebase, Stripe"
echo "   - Update to latest versions that support 16 KB"
echo "   - React Native 0.73.6 may need updating to 0.74+ for better 16 KB support"
echo ""
echo "3. To verify specific libraries, extract the final APK from Play Console"
echo "   and check ELF alignment using: readelf -l <library.so>"
echo ""

