import { StyleSheet, Dimensions, StatusBar } from 'react-native';
import { ThemeColors, ThemeFonts } from '../utils/Theme';
const { width, height } = Dimensions.get('window');
const statusBarHeight = Platform.OS === 'android' ? StatusBar.currentHeight : 0;

export default StyleSheet.create({
  ScrollViewContentContainerStyle: {
    minHeight: height - statusBarHeight - 100,
  },
  MainContainer: {
    minHeight: height - statusBarHeight - 100,
    backgroundColor: ThemeColors.WHITE,
  },
  HomeItemContainer: {
    height: 100,
    width: width - 40,
    borderRadius: 20,
    marginHorizontal: 20,
    marginVertical: 7.5,
    shadowOffset: { width: 10, height: -10 },
    shadowColor: ThemeColors.BLACK,
    shadowOpacity: 1,
    elevation: 10,
    shadowRadius: 100,
    backgroundColor: ThemeColors.WHITE,
  },
  LinearGradientContainer: {
    height: 100,
    width: width - 40,
    borderRadius: 20,
    flexDirection: 'row',
  },
  TextView: {
    height: 100,
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  MainTitleText: {
    color: ThemeColors.WHITE,
    fontFamily: ThemeFonts.SEMI_BOLD,
    fontSize: 20,
  },
  SubTitleText: {
    color: ThemeColors.WHITE,
    fontFamily: ThemeFonts.MEDIUM,
    fontSize: 10,
    opacity: 0.6,
  },
  IconView: {
    height: 100,
    width: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  IconRing: {
    width: 53,
    height: 53,
    borderRadius: 53 / 2,
    borderWidth: 1,
    borderColor: ThemeColors.WHITE,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  IconCircleLinearGradient: {
    width: 53,
    height: 53,
    margin: 0,
    padding: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  IconCircle: {
    width: 42,
    height: 42,
    borderRadius: 42 / 2,
    backgroundColor: '#59a03d',
    justifyContent: 'center',
    alignItems: 'center',
  },
  CreateAddView: {
    width: width - 50,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    borderColor: '#6DA75B',
    borderWidth: 1,
    borderStyle: 'dashed',
    paddingVertical: 15,
    marginTop: 20,
  },
  InformationText:{
    color: '#6DA75B',
    fontFamily: ThemeFonts.REGULAR,
    fontSize: 12,
    marginLeft: 0,
    marginTop: 10,
    paddingHorizontal: 10
  },
  CreateAddText: {
    color: '#6DA75B',
    fontFamily: ThemeFonts.REGULAR,
    fontSize: 15,
    marginLeft: 20,
  },
  RoundImageView: {
    width: 53,
    height: 53,
    borderRadius: 25,
    backgroundColor: ThemeColors?.WHITE,
    borderColor: ThemeColors?.BLACK,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  NameTExt: {
    color: ThemeColors?.BLACK,
    fontFamily: ThemeFonts.MEDIUM,
    fontSize: 13,
  },
  TimeText: {
    color: ThemeColors?.DARK_GRAY,
    fontFamily: ThemeFonts.REGULAR,
    fontSize: 8,
    marginTop: -5,
  },
  RoundSecondItem: {
    width: 53,
    height: 53,
    borderRadius: 25,
    backgroundColor: '#D6D2D2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  LostWalletText: {
    color: ThemeColors?.BLACK,
    fontFamily: ThemeFonts.MEDIUM,
    fontSize: 13,
  },
  DescriptionText: {
    color: ThemeColors?.LIGHT_GRAY,
    fontFamily: ThemeFonts.MEDIUM,
    fontSize: 10,
  },
  viewedText: {
    color: ThemeColors?.DARK_GRAY,
    fontFamily: ThemeFonts.REGULAR,
    fontSize: 8,
    marginTop: -5,
  },
  commentsText: {
    color: ThemeColors?.BLACK,
    fontFamily: ThemeFonts.REGULAR,
    fontSize: 10,
    textDecorationLine: 'underline',
  },
  AddACommentView: {
    alignItems: 'center',
    justifyContent: 'center',
    width: width - 50,
    alignSelf: 'center',
    height: 50,
    borderRadius: 30,
    backgroundColor: ThemeColors?.WHITE,
    shadowOffset: { width: 10, height: -10 },
    shadowColor: ThemeColors.BLACK,
    shadowOpacity: 1,
    elevation: 5,
    shadowRadius: 100,
    marginTop: 10,
  },
  AddACommentText: {
    color: ThemeColors?.BLACK,
    fontFamily: ThemeFonts.REGULAR,
    fontSize: 10,
  },
});
