import {StyleSheet, Dimensions, StatusBar} from 'react-native';
import {ThemeColors, ThemeFonts} from '../utils/Theme';
const {width, height} = Dimensions.get('window');
const statusBarHeight = Platform.OS === 'android' ? StatusBar.currentHeight : 0;

export default StyleSheet.create({
  ScrollViewContentContainerStyle: {
    minHeight: height - statusBarHeight - 40,
  },
  MainContainer: {
    flex: 1,
    backgroundColor: ThemeColors.WHITE,
    alignItems: 'center',
    paddingTop: 30,
  },
  AddItemContainer: {
    width: width - 40,
    shadowOffset: {width: 0, height: 0},
    shadowColor: ThemeColors.GRAY,
    shadowOpacity: 1,
    elevation: 10,
    shadowRadius: 5,
    backgroundColor: ThemeColors.WHITE,
    borderRadius: 20,
    marginBottom: 7,
  },
  LinearGradientContainer: {
    height: 200,
    width: width - 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  TextView: {
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  MainTitleText: {
    color: ThemeColors.WHITE,
    fontFamily: ThemeFonts.SEMI_BOLD,
    fontSize: 20,
    textAlign: 'center',
  },
  SubTitleText: {
    color: ThemeColors.WHITE,
    fontFamily: ThemeFonts.MEDIUM,
    fontSize: 10,
    opacity: 0.6,
  },
  IconCircle: {
    width: 58,
    height: 58,
    borderRadius: 58 / 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: ThemeColors.WHITE,
  },
  ListViewContainer: {
    height: 60,
    width: width - 40,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 7,
    shadowOffset: {width: 0, height: 0},
    shadowColor: ThemeColors.GRAY,
    shadowOpacity: 1,
    elevation: 10,
    shadowRadius: 5,
    backgroundColor: ThemeColors.WHITE,
  },
  ListTextView: {
    flexGrow: 1,
    height: 60,
    paddingHorizontal: 25,
    justifyContent: 'center',
  },
  ListTitleText: {
    color: ThemeColors.BLACK,
    fontFamily: ThemeFonts.MEDIUM,
    fontSize: 13,
  },
  RadioButtonView: {
    height: 60,
    width: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ButtonView: {
    width: width - 40,
    borderRadius: 20,
    marginVertical: 7,
  },
  ImageView: {
    borderRadius: 25,
    width: width - 70,
    height: width - 150,
  },
  ImageViewContainer: {
    width: width - 40,
    borderRadius: 20,
    display: 'flex',
    justifyContent: 'center',
    padding: 15,
    backgroundColor: ThemeColors.WHITE,
    marginTop: 25,
    shadowOffset: {width: 0, height: 0},
    shadowColor: ThemeColors.GRAY,
    shadowOpacity: 1,
    elevation: 10,
    shadowRadius: 10,
  },
  ImageBoxView: {
    width: width - 70,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  ImageTextView: {
    flexGrow: 1,
  },
  LableText: {
    color: ThemeColors.BLACK,
    fontFamily: ThemeFonts.LIGHT,
    fontSize: 12,
    marginBottom: -5,
  },
  ImageTitleText: {
    fontFamily: ThemeFonts.MEDIUM,
    fontSize: 16,
  },
  ImageTitleText2: {
    fontFamily: ThemeFonts.LIGHT,
    fontSize: 12,
    maxWidth: '80%',
  },
  ImageSubTitleText: {
    fontFamily: ThemeFonts.SEMI_BOLD,
    fontSize: 12,
    color: ThemeColors.PRIMARY_COLOR,
  },
  DeleteBox: {
    height: 30,
    width: 30,
    borderRadius: 30 / 2,
    backgroundColor: '#3BA20F',
    justifyContent: 'center',
    alignItems: 'center',
  },
  EditBox: {
    height: 30,
    marginRight: 10,
    width: 30,
    borderRadius: 30 / 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  footer: {
  padding: 15,
  alignItems: 'center',
  borderTopWidth: 1,
  borderTopColor: '#f0f0f0',
  marginTop: 10,
},
footerText: {
  fontSize: 12,
  opacity: 0.7,
},
});
