import { StyleSheet, Dimensions, StatusBar } from 'react-native';
import { GradientColors, ThemeColors, ThemeFonts } from '../utils/Theme';
const { width, height } = Dimensions.get('window');
const statusBarHeight = Platform.OS === 'android' ? StatusBar.currentHeight : 0;

export default StyleSheet.create({
  ScrollViewContentContainerStyle: {
    minHeight: height - statusBarHeight - 40,
  },
  MainContainer: {
    flex: 1,
    backgroundColor: ThemeColors.WHITE,
    alignItems: 'center',
    paddingTop: 30,
  },
  TextView: {
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  TitleView: {
    height: 90,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  TitleText: {
    color: ThemeColors.BLACK,
    fontFamily: ThemeFonts.SEMI_BOLD,
    fontSize: 25,
    paddingBottom: 8,
    marginTop: 10
  },
  ListViewContainer: {
    height: 64,
    width: width - 40,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 8,
    paddingHorizontal: 15,
    paddingTop: 18,
    paddingBottom: 23,
    shadowOffset: { width: 0, height: 0 },
    shadowColor: ThemeColors.GRAY,
    shadowOpacity: 1,
    elevation: 10,
    shadowRadius: 5,
    backgroundColor: ThemeColors.WHITE,
  },
  ListTextView: {
    flexGrow: 1,
  },
  ListTitleText: {
    color: ThemeColors.BLACK,
    fontFamily: ThemeFonts.MEDIUM,
    fontSize: 13,
  },
  RadioButton: {
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: ThemeColors.BLACK,
    paddingEnd: 5,
  },
  ButtonView: {
    width: width - 40,
    borderRadius: 20,
    marginVertical: 5,
  },
  CreateAddView: {
    width: width - 50,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    borderColor: '#6DA75B',
    borderWidth: 1,
    borderStyle: 'dashed',
    paddingVertical: 15,
    marginTop: 20,
  },
  CreateAddText: {
    color: '#6DA75B',
    fontFamily: ThemeFonts.REGULAR,
    fontSize: 15,
    marginLeft: 20,
  },
  ItemViewContainer: {
    height: 60,
    width: width - 40,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 7,
    shadowOffset: { width: 0, height: 0 },
    shadowColor: ThemeColors.GRAY,
    shadowOpacity: 1,
    elevation: 10,
    shadowRadius: 5,
    backgroundColor: ThemeColors.WHITE,
  },
  NewView: {
    borderRadius: 20,
    height: 60,
    marginTop: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingLeft: 21,
    paddingRight: 10,
  },
  ItemViewTextBox2: {
    color: ThemeColors.BLACK,
    fontFamily: ThemeFonts.MEDIUM,
    fontSize: 13,
    width: '75%',
  },
  LocationIconView: {
    backgroundColor: ThemeColors?.PRIMARY_COLOR,
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -3,
  },
  LocationIconView2: {
    backgroundColor: GradientColors?.RED[0],
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -3,
    marginLeft: 5
  },
});
